informacao = input("Digite algo: ")
print("O tipo primitivo desse valor é",type(informacao))
print("Só tem espaços?", informacao.isspace())
print("É um número?", informacao.isnumeric())
print("É alfabético?", informacao.isalpha())
print("É alfanumérico?", informacao.isalnum())
print("Está escrito só em maiúsculo?", informacao.isupper())
print("Está escrito só em minúscula?", informacao.islower())
print("Está capitalizado?", informacao.istitle())