medida = float(input("Uma distância em metros: "))
print(f"A medida de {medida}m corresponde a:")
print(f"{medida * 0.001:.3f} km")
print(f"{medida * 0.01:.2f} hm")
print(f"{medida * 0.1:.1f} dam")
print(f"{medida * 10} dm")
print(f"{medida * 100} cm")
print(f"{medida * 1000} mm")